### ISSUE TITLE
Update to Python 3.8

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/tempo#159]
Update supported version to Python 3.8. This includes updating the testing environment to make sure that  the codebase is compatible.

Alternatively, we could also consider having a test matrix across Python 3.6, 3.7 and 3.8.

**Comment by jklaise** [comment]
Based on https://github.com/SeldonIO/tempo/blob/master/.github/workflows/tests.yml#L14 I believe this can be closed?

Btw the badge on the `README` says Python 3.5-3.8 which I assume is incorrect by now...

**Comment by adriangonz** [comment]
Good point, this can be closed
