### ISSUE TITLE
ability to specify runtime as argument to the `.deploy` method? 

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/tempo#61]
It may be cleaner to specify runtime as argument to the `.deploy` method so we can avoid modification of the pipeline instance state. 

This way it will be more transparent what remote we deploy to - and also possible to deploy to two remotes at the same time. 

For example:
```python
# Talking to docker runtime
docker_runtime = classifier.deploy(runtime=DockerRuntime(...))
docker_runtime.wait_ready()
docker_runtime.remote(payload=np.array([[1, 2, 3, 4]]))

# Talking to k8s runtime
k8s_runtime = classifier.deploy(runtime=KubernetesRuntime(...))
k8s_runtime.wait_ready()
k8s_runtime.remote(payload=np.array([[1, 2, 3, 4]]))
```

One present problem is that information about upload is included in the artefact itself in the `.save` and then `.upload` calls.

**Comment by cliveseldon** [comment]
No needed anymore
